name: Makefile CI
run-name: ${{ github.actor }} run test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

        
    - name: Install dependencies
      run: make

    - name: Run measure
      run: make measure
    
    - name: Run script file
      run: |
         cp measure ../../measure
      shell: bash
    
    - name: Archive measurement
      uses: actions/upload-artifact@v3
      with:
        name: measure
        path: measure

    - name: Archive measurement
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: results.txt